############### APP CONFIG #################

application: map256app
version: 1
runtime: python
api_version: 1
derived_file_type:
  - python_precompiled

handlers:
############### PUBLIC URLS #################
- url: /
  script: app.py

- url: /faq
  script: app.py

- url: /front_page_data
  script: app.py

- url: /t/(.*)
  script: app.py

- url: /f/(.*)
  script: app.py

- url: /fl/(.*)
  script: app.py

- url: /kl/(.*)
  script: app.py

- url: /data/(.*)
  script: app.py

- url: /scoreboard
  script: app.py

- url: /profile(.*)
  script: app.py
  login: required

- url: /account_hide_toggle
  script: app.py
  login: required

- url: /foursquare_authorization
  script: app.py
  login: required

- url: /foursquare_callback
  script: app.py
  login: required

- url: /foursquare_account_delete
  script: app.py
  login: required

- url: /twitter_authorization
  script: app.py
  login: required

- url: /twitter_callback
  script: app.py
  login: required

- url: /twitter_account_delete
  script: app.py
  login: required

- url: /flickr_authorization
  script: app.py
  login: required

- url: /flickr_callback
  script: app.py
  login: required

############### QUEUE WORKERS #################

- url: /worker_(.*)
  script: queue.py
  login: admin

############### CRON JOBS #################

- url: /cron_(.*)
  script: cron.py
  login: admin

############### STATIC FILES #################

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /map256.js
  static_files: static/map256.js
  upload: static/map256.js

- url: /static
  static_dir: static