application: map256app
version: 1
runtime: python
api_version: 1

handlers:
############### PUBLIC URLS #################
- url: /
  script: app.py

- url: /t/(.*)
  script: app.py

- url: /f/(.*)
  script: app.py

- url: /authorize.*
  script: authorization.py

- url: /callback.*
  script: authorization.py

- url: /scoreboard
  script: app.py

- url: /profile
  script: app.py
  login: required

- url: /data/(.*)
  script: app.py

- url: /foursquare_authorization
  script: app.py
  login: required

- url: /foursquare_callback
  script: app.py
  login: required

############### QUEUE WORKERS #################

- url: /worker_foursquare_history
  script: queue.py
  login: admin

- url: /worker_statistics
  script: queue.py
  login: admin

############### CRON JOBS #################

- url: /cron_foursquare_history
  script: cron.py
  login: admin

- url: /cron_statistics
  script: cron.py
  login: admin

############### STATIC FILES #################

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /stylesheet.css
  static_files: static/stylesheet.css
  upload: static/stylesheet.css

- url: /faq.html
  static_files: static/faq.html
  upload: static/faq.html

- url: /map256.js
  static_files: static/map256.js
  upload: static/map256.js

- url: /json_parse.js
  static_files: static/json_parse.js
  upload: static/json_parse.js